### PR TITLE
remove vulnerable version of ansi-regex from dependencies

### PR DESCRIPTION
**Pull request by tsekityam**
>  Dependabot cannot update ansi-regex to a non-vulnerable version
> The latest possible version that can be installed is 4.1.0 because of the following conflicting dependency:
>
> rewire@5.0.0 requires ansi-regex@^4.1.0 via a transitive dependency on strip-ansi@5.2.0
> The earliest fixed version is 5.0.1.
>
> View logs or learn more about troubleshooting Dependabot errors.

I got the above warning in one of my projects. It seems that the best way to fix this vulnerability is to upgrade `mocha` and `eslint` in this project to the latest version.

This PR upgrade `mocha` and `eslint` to the latest version, and also add the missing dev dependency `istanbul` to the repo.

I tried `npm run test`, `npm run coverage` and `npm audit`, and no warning or error was raised.

### CODE REVIEW

**Review by imailer — APPROVED** [review]

**Comment by makiri1993** [comment]
Any timeline when this will be released? I'm having the same issue and it's part of a ticket of mine :D

**Review by aristeu-ciandt — APPROVED** [review]

**Review by rockaBe — APPROVED** [review]

**Comment by imailer** [comment]
@jhnns can you please review the PR and merge it ?

**Comment by jhnns** [comment]
I will try to review it this week :+1:

**Comment by jhnns** [comment]
LGTM, thank you 👍  :)

**Comment by jhnns** [comment]
Published as v6.0.0 🚀

**Pull request merged**
