### PR TITLE
Adding ability to invalidate require cache with rewire by setting second parameter to true

### PR DESCRIPTION
**Pull request by mboudreau**
When testing, I needed a way to invalidate the cache easily.  I can do it manually, but would prefer it to be done withing rewire since it's already adding some nice testing functionality over my classes.

### CODE REVIEW

**Comment by jhnns** [comment]
Thank you for your PR 👍 

Unfortunately, I don't think that this change makes a lot of sense. rewire does neither use the cached version from Node.js nor does it cache the module, so I don't know why it should miss with the cache anyway.

Closing it for now, but maybe you can bring up a use case I should consider.

**Comment by mboudreau** [comment]
@jhnns I believe that you are mistaken in your assumption.  If you look at the `requireProxy` in moduleEnv.js, you'll see that the require within your module wrapper is using the internal Node require, hence all requires within rewire except for the top level module is cached.

This is extremely problematic in a testing environment where rewire is most (if always?) used, which then needs to be reset to it's original state on first require.  The best solution (other than this PR, which is a quick fix), would be for the `requireProxy` to keep tabs on every require that happens within the rewired module, which would get reset on the next rewire call to the same module.

My particular issue with this is that my rewire module was requiring another piece of important code in my project, which was dependent on an external variable, like an environment variable, which would cause trouble when trying to test out the top level rewire with different variables to see if it all worked. 

My change here was a bit more 'global' in nature, but this code change did fix my issue that I had when trying to test out my code.

**Comment by jhnns** [comment]
I'm not sure if I did understand the problem correctly. But you can solve that issue just by calling `delete require.cache[require.resolve(targetPath)];` before calling `rewire()`, so I don't see the benefits of adding this piece of code to the library.

**Comment by mboudreau** [comment]
@jhnns well, I guess it depends on the purpose of rewire.  It's normally used in a testing environment and as such, as a user of rewire, I would expect that if I rewire a module, I'll always get a clean copy at the time of rewiring, which is not the case if that module has submodules.

In my particular use case, I had a lot of private functions that I wanted to test out, some of which are dependent on some other piece of code that I have.  The problem here is that I had a beforeEach that would use rewire to get a new version of that module, but it wouldn't get a new one of the submodule, and if there's anything wrong with that submodule's state (like using an environment variable), it would cause errors in my tests.

The reason I'd rather want it in rewire is because this is the behavior that I would expect of rewire, but my tests have shown otherwise.

**Comment by jhnns** [comment]
> I would expect that if I rewire a module, I'll always get a clean copy at the time of rewiring, which is not the case if that module has submodules.

Personally, I don't agree with that because for me, it would be surprising that some other module is executed by calling `rewire()`. Even in a production environment, sub modules might not be executed again when they are already in the cache.

And: Your proposed change does not fulfill this requirement, it will only remove the rewired module from the cache (which has basically no effect because the module is not read from the cache anyway).

**Pull request closed without merging**
